---
title: "Votação Deputados"
author: "Mattheus Brito Rodrigues"
date: "06/10/2018"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(Amelia)
library(dplyr)
library(tidyverse)
library(broom)
library(GGally)
```

# Introdução

```{r}
eleicoes2006 <- read.csv("/Users/mattheusbrito/Downloads/AD2/Lab02/eleicoes_2006.csv")
eleicoes2010 <- read.csv("/Users/mattheusbrito/Downloads/AD2/Lab02/eleicoes_2010.csv")
eleicoes2006_2010 <- read.csv("/Users/mattheusbrito/Downloads/AD2/Lab02/eleicoes_2006_e_2010.csv")
```



```{r}
missmap(eleicoes2006)
missmap(eleicoes2010)
missmap(eleicoes2006_2010)
```

# Questão 01
```{r}
eleicoes2006_rm <- eleicoes2006 %>%
   select(-c(cargo))
```


```{r}
eleicoes2006_rm <- eleicoes2006_rm %>%
  select(-c(sequencial_candidato, nome))
```


```{r}
modelo <- lm(votos~., data = eleicoes2006_rm)
```

```{r}
glance(modelo)
```

```{r}
anova(modelo)
```



# Questão 02.1

```{r}
modeloFiltrado <- lm(votos~., data=eleicoes2006_rm)
```


```{r}
ggplot(modeloFiltrado, aes(x = predict(modeloFiltrado), y = residuals(modeloFiltrado))) +
  geom_point(color= "darkblue") + 
  xlab("Predict") + 
  ylab("Residuals")
  
```


# Questão 02.2

```{r}
anova(modeloFiltrado)
```


# Questão 02.3
```{r}

```

# Questão 02.4
```{r}

```

# Questão 03
```{r}
eleicoes2006_rm <- eleicoes2006_rm %>%
  select(-c(quantidade_doadores, estado_civil, ano))
```

```{r fig.align = "center", fig.height=10,fig.width=10}
dadosCorrelacao <- eleicoes2006_rm %>%
  mutate(uf = as.numeric(uf)) %>%
  mutate(partido = as.numeric(partido)) %>%
  mutate(sexo = as.numeric(sexo)) %>%
  mutate(grau = as.numeric(grau)) %>%
  mutate(ocupacao = as.numeric(ocupacao))
  round(2)

ggpairs(dadosCorrelacao, axisLabels = "none")
```

# Questão 04

```{r}
eleicoesRS2 <- eleicoes2006_rm %>%
  select(-total_despesa)

modeloRS2 <- lm(votos~., data = eleicoesRS2)

glance(modeloRS2)
```

```{r}
glance(modelo)
diff = glance(modelo)$adj.r.squared - glance(modeloRS2)$adj.r.squared

round(diff,3)
```

